<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class haxe__Unserializer_DefaultResolver {
	public function __construct() {}
	public function resolveClass($name) {
		return Type::resolveClass($name);
	}
	public function resolveEnum($name) {
		return Type::resolveEnum($name);
	}
	function __toString() { return 'haxe._Unserializer.DefaultResolver'; }
}
