<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class Reflect {
	public function __construct(){}
	static function hasField($o, $field) {
		return _hx_has_field($o, $field);
	}
	static function field($o, $field) {
		return _hx_field($o, $field);
	}
	static function setField($o, $field, $value) {
		$o->{$field} = $value;
	}
	static function getProperty($o, $field) {
		if(null === $o) {
			return null;
		}
		$cls = null;
		if(Std::is($o, _hx_qtype("Class"))) {
			$cls = $o->__tname__;
		} else {
			$cls = get_class($o);
		}
		$cls_vars = get_class_vars($cls);
		if(isset($cls_vars['__properties__']) && isset($cls_vars['__properties__']['get_'.$field]) && ($field = $cls_vars['__properties__']['get_'.$field])) {
			return $o->$field();
		} else {
			return _hx_field($o, $field);
		}
	}
	static function setProperty($o, $field, $value) {
		if(null === $o) {
			return;
		}
		$cls = null;
		if(Std::is($o, _hx_qtype("Class"))) {
			$cls = $o->__tname__;
		} else {
			$cls = get_class($o);
		}
		$cls_vars = get_class_vars($cls);
		if(isset($cls_vars['__properties__']) && isset($cls_vars['__properties__']['set_'.$field]) && ($field = $cls_vars['__properties__']['set_'.$field])) {
			$o->$field($value);
		} else {
			$o->{$field} = $value;
		}
	}
	static function callMethod($o, $func, $args) {
		return call_user_func_array(((is_callable($func)) ? $func : array($o, $func)), ((null === $args) ? array() : $args->a));
	}
	static function fields($o) {
		if($o === null) {
			return new _hx_array(array());
		}
		if($o instanceof _hx_array) {
			return new _hx_array(array('concat','copy','insert','iterator','length','join','pop','push','remove','reverse','shift','slice','sort','splice','toString','unshift'));
		} else {
			if(is_string($o)) {
				return new _hx_array(array('charAt','charCodeAt','indexOf','lastIndexOf','length','split','substr','toLowerCase','toString','toUpperCase'));
			} else {
				return new _hx_array(_hx_get_object_vars($o));
			}
		}
	}
	static function isFunction($f) {
		if(!(is_array($f) && is_callable($f)) || _hx_is_lambda($f)) {
			$tmp = null;
			if(is_array($f)) {
				$o = $f[0];
				$field = $f[1];
				$tmp = _hx_has_field($o, $field);
			} else {
				$tmp = false;
			}
			if($tmp) {
				return $f[1] !== "length";
			} else {
				return false;
			}
		} else {
			return true;
		}
	}
	static function compare($a, $b) {
		if((is_object($_t = $a) && ($_t instanceof Enum) ? $_t == $b : _hx_equal($_t, $b))) {
			return 0;
		} else {
			if(is_string($a)) {
				return strcmp($a, $b);
			} else {
				if($a > $b) {
					return 1;
				} else {
					return -1;
				}
			}
		}
	}
	static function compareMethods($f1, $f2) {
		$tmp = null;
		if(is_array($f1)) {
			$tmp = is_array($f1);
		} else {
			$tmp = false;
		}
		if($tmp) {
			return $f1[0] === $f2[0] && $f1[1] == $f2[1];
		}
		$tmp1 = null;
		if(is_string($f1)) {
			$tmp1 = is_string($f2);
		} else {
			$tmp1 = false;
		}
		if($tmp1) {
			return _hx_equal($f1, $f2);
		}
		return false;
	}
	static function isObject($v) {
		if($v === null) {
			return false;
		}
		if(is_object($v)) {
			$tmp = null;
			if(!$v instanceof _hx_anonymous) {
				$tmp = Type::getClass($v) !== null;
			} else {
				$tmp = true;
			}
			if(!$tmp) {
				if(!$v instanceof _hx_class) {
					return $v instanceof _hx_enum;
				} else {
					return true;
				}
			} else {
				return true;
			}
		}
		return is_string($v) && !_hx_is_lambda($v);
	}
	static function isEnumValue($v) {
		return $v instanceof Enum;
	}
	static function deleteField($o, $field) {
		if(!_hx_has_field($o, $field)) {
			return false;
		}
		if(isset($o->__dynamics[$field])) unset($o->__dynamics[$field]); else if($o instanceof _hx_anonymous) unset($o->$field); else $o->$field = null;
		return true;
	}
	static function copy($o) {
		if(is_string($o)) {
			return $o;
		}
		$o2 = _hx_anonymous(array());
		{
			$_g = 0;
			$_g1 = Reflect::fields($o);
			while($_g < $_g1->length) {
				$f = $_g1[$_g];
				$_g = $_g + 1;
				{
					$value = Reflect::field($o, $f);
					$o2->{$f} = $value;
					unset($value);
				}
				unset($f);
			}
		}
		return $o2;
	}
	static function makeVarArgs($f) {
		return array(new _hx_lambda(array(&$f), '_hx_make_var_args'), 'execute');
	}
	function __toString() { return 'Reflect'; }
}
