<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class StringBuf {
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		$this->b = "";
	}}
	public $b;
	public function get_length() {
		return strlen($this->b);
	}
	public function add($x) {
		if(is_null($x)) {
			$x = "null";
		} else {
			if(is_bool($x)) {
				$x1 = null;
				if($x) {
					$x1 = "true";
				} else {
					$x1 = "false";
				}
				$x = $x1;
			}
		}
		$tmp = $this;
		$tmp1 = $tmp->b;
		$tmp->b = _hx_string_or_null($tmp1) . Std::string($x);
	}
	public function addSub($s, $pos, $len = null) {
		$tmp = $this;
		$tmp1 = $tmp->b;
		$tmp->b = _hx_string_or_null($tmp1) . _hx_string_or_null(_hx_substr($s, $pos, $len));
	}
	public function addChar($c) {
		$tmp = $this;
		$tmp->b = _hx_string_or_null($tmp->b) . _hx_string_or_null(chr($c));
	}
	public function toString() {
		return $this->b;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static $__properties__ = array("get_length" => "get_length");
	function __toString() { return $this->toString(); }
}
