<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class cornerstone_integrator_configuration_Configuration {
	public function __construct(){}
	static $__rtti = "<class path=\"cornerstone.integrator.configuration.Configuration\" params=\"\">\x0A\x09<Data public=\"1\" static=\"1\"><c path=\"cornerstone.integrator.configuration.ConfigurationData\"/></Data>\x0A\x09<meta>\x0A\x09\x09<m n=\":keepSub\"/>\x0A\x09\x09<m n=\":rtti\"/>\x0A\x09</meta>\x0A</class>";
	static $Data;
	function __toString() { return 'cornerstone.integrator.configuration.Configuration'; }
}
