<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class cornerstone_integrator_configuration_DatabaseEngineEnum extends Enum {
	public static $GENERIC;
	public static $MYSQL;
	public static $ORACLE;
	public static $POSTGRESQL;
	public static $SQLSERVER;
	public static $__constructors = array(4 => 'GENERIC', 2 => 'MYSQL', 1 => 'ORACLE', 3 => 'POSTGRESQL', 0 => 'SQLSERVER');
	}
cornerstone_integrator_configuration_DatabaseEngineEnum::$GENERIC = new cornerstone_integrator_configuration_DatabaseEngineEnum("GENERIC", 4);
cornerstone_integrator_configuration_DatabaseEngineEnum::$MYSQL = new cornerstone_integrator_configuration_DatabaseEngineEnum("MYSQL", 2);
cornerstone_integrator_configuration_DatabaseEngineEnum::$ORACLE = new cornerstone_integrator_configuration_DatabaseEngineEnum("ORACLE", 1);
cornerstone_integrator_configuration_DatabaseEngineEnum::$POSTGRESQL = new cornerstone_integrator_configuration_DatabaseEngineEnum("POSTGRESQL", 3);
cornerstone_integrator_configuration_DatabaseEngineEnum::$SQLSERVER = new cornerstone_integrator_configuration_DatabaseEngineEnum("SQLSERVER", 0);
