<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class cornerstone_integrator_configuration_DeployEnvironmentEnum extends Enum {
	public static $DEVELOPMENT;
	public static $PRODUCTION;
	public static $TEST;
	public static $__constructors = array(0 => 'DEVELOPMENT', 2 => 'PRODUCTION', 1 => 'TEST');
	}
cornerstone_integrator_configuration_DeployEnvironmentEnum::$DEVELOPMENT = new cornerstone_integrator_configuration_DeployEnvironmentEnum("DEVELOPMENT", 0);
cornerstone_integrator_configuration_DeployEnvironmentEnum::$PRODUCTION = new cornerstone_integrator_configuration_DeployEnvironmentEnum("PRODUCTION", 2);
cornerstone_integrator_configuration_DeployEnvironmentEnum::$TEST = new cornerstone_integrator_configuration_DeployEnvironmentEnum("TEST", 1);
