<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class cornerstone_integrator_LibReference {
	public function __construct() {}
	public function Dummy($String1, $Int2, $Float3, $Bool4, $Byte5, $DateTime6, $Enum7, $Long8, $Dictionary9, $Uuid11) {
		$data = "";
		Type::getClass(_hx_qtype("cornerstone.integrator.helpers.Int64_Helper"));
		Type::getClass(_hx_qtype("cornerstone.integrator.datatypes.UUID"));
		haxe_Log::trace("test", null);
		return null;
	}
	function __toString() { return 'cornerstone.integrator.LibReference'; }
}
