<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class cornerstone_integrator_transport_MethodCall {
	public function __construct() {
		;
	}
	public $LogicModule;
	public $LogicClass;
	public $LogicMethod;
	public $LogicParams;
	public $Name;
	public function set_LogicModule($value) {
		return $this->LogicModule = $value;
	}
	public function get_LogicModule() {
		return $this->LogicModule;
	}
	public function set_LogicClass($value) {
		return $this->LogicClass = $value;
	}
	public function get_LogicClass() {
		return $this->LogicClass;
	}
	public function set_LogicMethod($value) {
		return $this->LogicMethod = $value;
	}
	public function get_LogicMethod() {
		return $this->LogicMethod;
	}
	public function set_LogicParams($value) {
		return $this->LogicParams = $value;
	}
	public function get_LogicParams() {
		return $this->LogicParams;
	}
	public function get_Name() {
		return $this->Name;
	}
	public function set_Name($value) {
		return $this->Name = $value;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static $__properties__ = array("set_Name" => "set_Name","get_Name" => "get_Name","set_LogicParams" => "set_LogicParams","get_LogicParams" => "get_LogicParams","set_LogicMethod" => "set_LogicMethod","get_LogicMethod" => "get_LogicMethod","set_LogicClass" => "set_LogicClass","get_LogicClass" => "get_LogicClass","set_LogicModule" => "set_LogicModule","get_LogicModule" => "get_LogicModule");
	function __toString() { return 'cornerstone.integrator.transport.MethodCall'; }
}
