<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class cornerstone_integrator_transport_MethodResult {
	public function __construct() {
		;
	}
	public $ReturnObject;
	public $Name;
	public function get_ReturnObject() {
		return $this->ReturnObject;
	}
	public function set_ReturnObject($value) {
		return $this->ReturnObject = $value;
	}
	public function get_Name() {
		return $this->Name;
	}
	public function set_Name($value) {
		return $this->Name = $value;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static $__properties__ = array("set_Name" => "set_Name","get_Name" => "get_Name","set_ReturnObject" => "set_ReturnObject","get_ReturnObject" => "get_ReturnObject");
	function __toString() { return 'cornerstone.integrator.transport.MethodResult'; }
}
