<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class cornerstone_integrator_transport_RequestMessage {
	public function __construct() {
		;
	}
	public $RequestSeq;
	public $SessionID;
	public $Calls;
	public function set_RequestSeq($value) {
		return $this->RequestSeq = $value;
	}
	public function get_RequestSeq() {
		return $this->RequestSeq;
	}
	public function get_SessionID() {
		return $this->SessionID;
	}
	public function set_SessionID($value) {
		return $this->SessionID = $value;
	}
	public function get_Calls() {
		return $this->Calls;
	}
	public function set_Calls($value) {
		return $this->Calls = $value;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static $__properties__ = array("set_Calls" => "set_Calls","get_Calls" => "get_Calls","set_SessionID" => "set_SessionID","get_SessionID" => "get_SessionID","set_RequestSeq" => "set_RequestSeq","get_RequestSeq" => "get_RequestSeq");
	function __toString() { return 'cornerstone.integrator.transport.RequestMessage'; }
}
