<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
interface haxe_IMap {
	function get($k);
	function set($k, $v);
	function exists($k);
	function remove($k);
	function keys();
	function iterator();
	function toString();
}
