<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class org_ascrypt_GUID {
	public function __construct(){}
	static function create() {
		$s = null;
		$b = (new _hx_array(array()));
		{
			$_g = 0;
			while($_g < 128) {
				$_g = $_g + 1;
				$i = $_g - 1;
				$b[$i] = Math::floor(Math::random() * 128);
				unset($i);
			}
		}
		$s = org_ascrypt_Base16::encode(org_ascrypt_MD5::compute($b));
		$p = (new _hx_array(array()));
		$p[0] = _hx_substr($s, 0, 8);
		$p[1] = _hx_substr($s, 8, 4);
		$p[2] = _hx_substr($s, 12, 4);
		$p[3] = _hx_substr($s, 16, 4);
		$p[4] = _hx_substr($s, 20, 12);
		return $p->join("-");
	}
	static function format($s) {
		$p = (new _hx_array(array()));
		$p[0] = _hx_substr($s, 0, 8);
		$p[1] = _hx_substr($s, 8, 4);
		$p[2] = _hx_substr($s, 12, 4);
		$p[3] = _hx_substr($s, 16, 4);
		$p[4] = _hx_substr($s, 20, 12);
		return $p->join("-");
	}
	function __toString() { return 'org.ascrypt.GUID'; }
}
