<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class haxe_io_Eof {
	public function __construct() {}
	public function toString() {
		return "Eof";
	}
	function __toString() { return $this->toString(); }
}
