<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class haxe_io_Output {
	public function __construct(){}
	public $bigEndian;
	public function writeByte($c) {
		throw new HException("Not implemented");
	}
	public function writeBytes($s, $pos, $len) {
		$tmp = null;
		$tmp1 = null;
		if($pos >= 0) {
			$tmp1 = $len < 0;
		} else {
			$tmp1 = true;
		}
		if(!$tmp1) {
			$tmp = $pos + $len > $s->length;
		} else {
			$tmp = true;
		}
		if($tmp) {
			throw new HException(haxe_io_Error::$OutsideBounds);
		}
		$b = $s->b;
		$k = $len;
		while($k > 0) {
			$this->writeByte(ord($b->s[$pos]));
			$pos = $pos + 1;
			$k = $k - 1;
		}
		return $len;
	}
	public function flush() {
	}
	public function close() {
	}
	public function set_bigEndian($b) {
		$this->bigEndian = $b;
		return $b;
	}
	public function write($s) {
		$l = $s->length;
		$p = 0;
		while($l > 0) {
			$k = $this->writeBytes($s, $p, $l);
			if($k === 0) {
				throw new HException(haxe_io_Error::$Blocked);
			}
			$p = $p + $k;
			$l = $l - $k;
			unset($k);
		}
	}
	public function writeFullBytes($s, $pos, $len) {
		while($len > 0) {
			$k = $this->writeBytes($s, $pos, $len);
			$pos = $pos + $k;
			$len = $len - $k;
			unset($k);
		}
	}
	public function writeFloat($x) {
		$this->writeInt32(haxe_io_FPHelper::floatToI32($x));
	}
	public function writeDouble($x) {
		$i64 = haxe_io_FPHelper::doubleToI64($x);
		if($this->bigEndian) {
			$this->writeInt32($i64->high);
			$this->writeInt32($i64->low);
		} else {
			$this->writeInt32($i64->low);
			$this->writeInt32($i64->high);
		}
	}
	public function writeInt8($x) {
		$tmp = null;
		if($x >= -128) {
			$tmp = $x >= 128;
		} else {
			$tmp = true;
		}
		if($tmp) {
			throw new HException(haxe_io_Error::$Overflow);
		}
		$this->writeByte($x & 255);
	}
	public function writeInt16($x) {
		$tmp = null;
		if($x >= -32768) {
			$tmp = $x >= 32768;
		} else {
			$tmp = true;
		}
		if($tmp) {
			throw new HException(haxe_io_Error::$Overflow);
		}
		$this->writeUInt16($x & 65535);
	}
	public function writeUInt16($x) {
		$tmp = null;
		if($x >= 0) {
			$tmp = $x >= 65536;
		} else {
			$tmp = true;
		}
		if($tmp) {
			throw new HException(haxe_io_Error::$Overflow);
		}
		if($this->bigEndian) {
			$this->writeByte($x >> 8);
			$this->writeByte($x & 255);
		} else {
			$this->writeByte($x & 255);
			$this->writeByte($x >> 8);
		}
	}
	public function writeInt24($x) {
		$tmp = null;
		if($x >= -8388608) {
			$tmp = $x >= 8388608;
		} else {
			$tmp = true;
		}
		if($tmp) {
			throw new HException(haxe_io_Error::$Overflow);
		}
		$this->writeUInt24($x & 16777215);
	}
	public function writeUInt24($x) {
		$tmp = null;
		if($x >= 0) {
			$tmp = $x >= 16777216;
		} else {
			$tmp = true;
		}
		if($tmp) {
			throw new HException(haxe_io_Error::$Overflow);
		}
		if($this->bigEndian) {
			$this->writeByte($x >> 16);
			$this->writeByte($x >> 8 & 255);
			$this->writeByte($x & 255);
		} else {
			$this->writeByte($x & 255);
			$this->writeByte($x >> 8 & 255);
			$this->writeByte($x >> 16);
		}
	}
	public function writeInt32($x) {
		if($this->bigEndian) {
			$this->writeByte(_hx_shift_right($x, 24));
			$this->writeByte($x >> 16 & 255);
			$this->writeByte($x >> 8 & 255);
			$this->writeByte($x & 255);
		} else {
			$this->writeByte($x & 255);
			$this->writeByte($x >> 8 & 255);
			$this->writeByte($x >> 16 & 255);
			$this->writeByte(_hx_shift_right($x, 24));
		}
	}
	public function prepare($nbytes) {
	}
	public function writeInput($i, $bufsize = null) {
		if($bufsize === null) {
			$bufsize = 4096;
		}
		$buf = haxe_io_Bytes::alloc($bufsize);
		try {
			while(true) {
				$len = $i->readBytes($buf, 0, $bufsize);
				if($len === 0) {
					throw new HException(haxe_io_Error::$Blocked);
				}
				$p = 0;
				while($len > 0) {
					$k = $this->writeBytes($buf, $p, $len);
					if($k === 0) {
						throw new HException(haxe_io_Error::$Blocked);
					}
					$p = $p + $k;
					$len = $len - $k;
					unset($k);
				}
				unset($p,$len);
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			if(($e = $_ex_) instanceof haxe_io_Eof){
			} else throw $__hx__e;;
		}
	}
	public function writeString($s) {
		$b = haxe_io_Bytes::ofString($s);
		$this->writeFullBytes($b, 0, $b->length);
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static $__properties__ = array("set_bigEndian" => "set_bigEndian");
	function __toString() { return 'haxe.io.Output'; }
}
